[tool.poetry]
name = "banking-transaction-analysis-app"
version = "0.1.0"
description = ""
authors = ["egor <scudf24@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
